### ISSUE TITLE
Dataset download error

### ISSUE THREAD

**Issue by sd0809** [GAP-LAB-CUHK-SZ/MVImgNet#36]
Thanks for this impressive work !
I have the problem with download_tool.py while downloading the MVIMGNET.

Traceback (most recent call last):
  File "/mnt/workspace/shedong/data/scripts/download_mvimgnet.py", line 312, in <module>
    havePwdGetFiles( urls["mvimgnet"], pwd, download_root , force )
  File "/mnt/workspace/shedong/data/scripts/download_mvimgnet.py", line 304, in havePwdGetFiles
    getFiles(url, download_path, force)
  File "/mnt/workspace/shedong/data/scripts/download_mvimgnet.py", line 250, in getFiles
    url, name, hash = filemeta["@content.downloadUrl"], filemeta["name"], filemeta["file"]["hashes"]
KeyError: '@content.downloadUrl'

Can somebody help me ? Thank you !

**Comment by allenzyd1997** [comment]
Hi Shedong, 

I really have not met the problem before. I just checked the code, everything goes right, could you please double-check the URL in your script to ensure nothing has changed with the original code(or you can directly clone the code again)? Feel free to let me know if you still have a problem, we will see how to fix it. 

Yidan

**Comment by sd0809** [comment]
Thanks for your prompt reply!
I am sure I didn't change the code in download_tool.py.
I run the code again and print the filemeta when I got this error in line 247 of download_tool.py
`url, name, hash = filemeta["@content.downloadUrl"], filemeta["name"], filemeta["file"]["hashes"]`
the filemeta is:
{
  "error": {
    "code": "unauthenticated",
    "message": "Unauthenticated"
  }
}
So it seems like I am unauthenticated? I have completed the request form and got the password for the download.

I hope you can help me look into the issue when you have some time. Your assistance would be greatly appreciated.

**Comment by allenzyd1997** [comment]
OK! I am checking the problem. Sorry for the late reply. if you urgently need to download the data, FYI,  the web link we provided in the Google form reply can be accessed directly. You can manually download the rest 32 zips using the One Drive.

**Comment by sd0809** [comment]
OK, thank you!

**Comment by tau-yihouxiang** [comment]
The same error when running download_tool.py

Traceback (most recent call last):
  File "/dataset/taohu/Data/MVImageNet/download_tool.py", line 309, in <module>
    havePwdGetFiles( urls["mvimgnet"], pwd, download_root , force )
  File "/dataset/taohu/Data/MVImageNet/download_tool.py", line 301, in havePwdGetFiles
    getFiles(url, download_path, force)
  File "/dataset/taohu/Data/MVImageNet/download_tool.py", line 241, in getFiles
    getFiles(originalPath, os.path.join(download_path, i['FileLeafRef']), force, download_root, req=req, layers=layers+1)
  File "/dataset/taohu/Data/MVImageNet/download_tool.py", line 247, in getFiles
    url, name, hash = filemeta["@content.downloadUrl"], filemeta["name"], filemeta["file"]["hashes"]

**Comment by tau-yihouxiang** [comment]
The same error when running download_tool.py

Traceback (most recent call last):
havePwdGetFiles( urls["mvimgnet"], pwd, download_root , force )
getFiles(url, download_path, force)
getFiles(originalPath, os.path.join(download_path, i['FileLeafRef']), force, download_root, req=req, layers=layers+1)
url, name, hash = filemeta["@content.downloadUrl"], filemeta["name"], filemeta["file"]["hashes"]

**Comment by allenzyd1997** [comment]
I got it, It Looks like, after a few times of requests,  the share point of our university needs to re-authentication,  I am contacting the IT staff hoping they can solve the problem. FYI, You can still manually use the Share Point website (we provided in the Google form), to download the data file manually.

**Comment by MontaEllis** [comment]
same issue!

**Comment by 2hiTee** [comment]
Does anyone here met the issue: pyppeteer.errors.BrowserError: Browser closed unexpectedly: ? I run the code on remote server and get this error. Could somebody help? This is crucial for me. Thanks!
