### ISSUE TITLE
Error about pyppeteer

### ISSUE THREAD

**Issue by 2hiTee** [GAP-LAB-CUHK-SZ/MVImgNet#39]
Thanks for your work! I met below error when I run download_tool.py. Could you tell me how to fix it? Thanks!

Traceback (most recent call last):
  File "/storage/yangyanming/Objaverse/download_tool.py", line 309, in <module>
    havePwdGetFiles( urls["mvimgnet"], pwd, download_root , force )
  File "/storage/yangyanming/Objaverse/download_tool.py", line 299, in havePwdGetFiles
    asyncio.get_event_loop().run_until_complete(fetch_with_pwd(iurl, password))
  File "/opt/conda/envs/SCI/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/storage/yangyanming/Objaverse/download_tool.py", line 275, in fetch_with_pwd
    browser = await launch(options={'args': ['--no-sandbox']})
  File "/opt/conda/envs/SCI/lib/python3.9/site-packages/pyppeteer/launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "/opt/conda/envs/SCI/lib/python3.9/site-packages/pyppeteer/launcher.py", line 168, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/opt/conda/envs/SCI/lib/python3.9/site-packages/pyppeteer/launcher.py", line 227, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

**Comment by erceguder** [comment]
Facing the same issue. Thanks for the great work!

**Comment by MagiaSN** [comment]
Following this link and install missing dependencies solved my issue
https://stackoverflow.com/questions/57217924/pyppeteer-errors-browsererror-browser-closed-unexpectedly
